name: untitled19
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  get_it: ^8.0.3
  cloud_firestore: ^5.6.6
  uuid: ^4.5.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  flutter_contacts: ^1.1.9+2
  image_picker: ^1.1.2
  emoji_picker_flutter: ^4.3.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.2.0
  flutter_timezone: ^4.1.0
  timezone: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.15
 




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/