// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3N4NfTSgRsW2uzejU6zdM4ZJgKtIns3c',
    appId: '1:339370096722:web:6504df340e6099c744478b',
    messagingSenderId: '339370096722',
    projectId: 'finalproject-64a52',
    authDomain: 'finalproject-64a52.firebaseapp.com',
    storageBucket: 'finalproject-64a52.firebasestorage.app',
    measurementId: 'G-FW607GK55E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuAkIjxtzf45yv_MGMsQQRccWb3ipSqK0',
    appId: '1:339370096722:android:42825725e9a1b79344478b',
    messagingSenderId: '339370096722',
    projectId: 'finalproject-64a52',
    storageBucket: 'finalproject-64a52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXliRhdkMBh4-3kciWZtLeXxxsyye6nuE',
    appId: '1:339370096722:ios:c76c648e8f86963d44478b',
    messagingSenderId: '339370096722',
    projectId: 'finalproject-64a52',
    storageBucket: 'finalproject-64a52.firebasestorage.app',
    iosBundleId: 'com.example.untitled19',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXliRhdkMBh4-3kciWZtLeXxxsyye6nuE',
    appId: '1:339370096722:ios:c76c648e8f86963d44478b',
    messagingSenderId: '339370096722',
    projectId: 'finalproject-64a52',
    storageBucket: 'finalproject-64a52.firebasestorage.app',
    iosBundleId: 'com.example.untitled19',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3N4NfTSgRsW2uzejU6zdM4ZJgKtIns3c',
    appId: '1:339370096722:web:59ab728f8bd2049444478b',
    messagingSenderId: '339370096722',
    projectId: 'finalproject-64a52',
    authDomain: 'finalproject-64a52.firebaseapp.com',
    storageBucket: 'finalproject-64a52.firebasestorage.app',
    measurementId: 'G-JW0BG4EYH9',
  );
}
